FROM python:3.11-slim

WORKDIR /app

COPY requirments.txt .
RUN pip install --no-cache-dir -r requirments.txt

COPY app.py .

CMD ["python3", "-u", "app.py"]
#CMD ["echo", "Hello World"]
#CMD ["tail","-f", "/dev/null"]
