version: "3"
services:
  meshtastic_bridge:
    build: .
    restart: unless-stopped
    environment:
      MQTT_BROKER: "mosquitto"
      MQTT_PORT: 1883
      MQTT_USER: "default_user"
      MQTT_PASSWORD: "0815DLRG"
      MQTT_TOPIC: "msh/tracker/2/json/DLRGulm/#"
      MLO_USERNAME: "DLRGulm"

